env:
  CIRRUS_CLONE_DEPTH: 1
  ARCH: amd64

main_task:
  matrix:
    container:
      image: fedora:29
    freebsd_instance:
      image: freebsd-12-0-release-amd64
    freebsd_instance:
      image: freebsd-11-2-release-amd64
    osx_instance:
      image: mojave-xcode-10.1
    osx_instance:
      image: high-sierra-xcode-10.0
  matrix:
    env:
      BS: autotools
    env:
      BS: cmake
  prepare_script:
  - ./build/ci/cirrus_ci.sh prepare
  configure_script:
  - ./build/ci/build.sh -a autogen
  - ./build/ci/build.sh -a configure
  build_script:
  - ./build/ci/build.sh -a build
  test_script:
  - ./build/ci/build.sh -a test
  - ./build/ci/cirrus_ci.sh test

Windows_MinGW_task:
  windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019
  prepare_script:
  - choco install -y mingw
  - choco install -y cmake --installargs 'ADD_CMAKE_TO_PATH=User'
  configure_script:
  - refreshenv
  - mkdir build_ci\mingw
  - cd build_ci\mingw
  - cmake -G "MinGW Makefiles" -D CMAKE_BUILD_TYPE="Release" ..\..
  build_script:
  - refreshenv
  - cd build_ci\mingw
  - mingw32-make
