env:
  CIRRUS_CLONE_DEPTH: 1
  ARCH: amd64
  CPPFLAGS: -I/usr/local/include
  LDFLAGS: -L/usr/local/lib

task:
  freebsd_instance:
    matrix:
      image: freebsd-12-0-release-amd64
      image: freebsd-11-2-release-amd64
  install_script:
    - ./build/ci/cirrus_ci.sh install
  script:
    - ./build/ci_build.sh
    - ./build/ci/cirrus_ci.sh test
