env:
  CIRRUS_CLONE_DEPTH: 1
  ARCH: amd64
  CPPFLAGS: -I/usr/local/include
  LDFLAGS: -L/usr/local/lib

task:
  freebsd_instance:
    matrix:
      image: freebsd-12-0-release-amd64
      image: freebsd-11-2-release-amd64
  install_script:
    - sed -i.bak -e 's,pkg+http://pkg.FreeBSD.org/\${ABI}/quarterly,pkg+http://pkg.FreeBSD.org/\${ABI}/latest,' /etc/pkg/FreeBSD.conf
    - if [ `uname` = "FreeBSD" ]; then pkg upgrade -y; pkg install -y autoconf automake libiconv libtool pkgconf expat libxml2 liblz4 zstd; fi
  script:
    - ./build/ci_build.sh
